### PR TITLE
Print organizer/creator based on presence

### PR DESCRIPTION
**Pull request by parkr**
Sometimes the organizer is empty. Fall back to creator or print nothing.

### CODE REVIEW

**Review by benbalter — APPROVED** [review]

**Comment by parkr** [comment]
Thanks for the approval, @benbalter! Anything else you'd like to see?

**Comment by benbalter** [comment]
LGTM. :shipit:!

**Comment by parkr** [comment]
@benbalter Thanks! I can't merge in your repo at the moment, so not sure what the next steps are here.

**Comment by benbalter** [comment]
@parkr you should have a pending invite at https://github.com/benbalter/zoom-go/invitations. Alternatively, since I think you have more code than I do at this point, glad to transfer to your namespace if you'd like.

**Comment by parkr** [comment]
@benbalter My bad! I apologize for missing that. Must have gotten lost in my email and the PR page didn't have the banner like the main repo page does. Nevertheless, I now have access. I will see if I can get Travis to build here, then merge if all is green. 💚

**Comment by parkr** [comment]
@benbalter I think I see the issue with Travis. Branch protection is requiring the `continuous-integration/travis-ci` job, when none is created. The new Travis CI GitHub App creates `Travis CI - Pull Request` instead.

**Comment by benbalter** [comment]
@parkr fixed!

**Pull request merged**
